In [93]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
import re
from sqlalchemy import text
from datetime import datetime

In [94]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/search/location"

querystring = {"lat":"53.5500","lon":"10.00","radiuskm":"50","limit":"10","withFlightInfoOnly":"true"}

headers = {
	"x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'searchBy': {'lat': 53.55, 'lon': 10.0}, 'count': 1, 'items': [{'icao': 'EDDH', 'iata': 'HAM', 'name': 'Hamburg', 'shortName': 'Hamburg', 'municipalityName': 'Hamburg', 'location': {'lat': 53.6304, 'lon': 9.988229}, 'countryCode': 'DE', 'timeZone': 'Europe/Berlin'}]}

Turning this into data frame

In [95]:
pd.json_normalize(response.json()['items'])

,icao,iata,name,shortName,municipalityName,countryCode,timeZone,location.lat,location.lon
0,EDDH,HAM,Hamburg,Hamburg,Hamburg,DE,Europe/Berlin,53.6304,9.988229

Now want to create a function which will fetch the latitude, longitude, and radium set by mysel. the data should be from sql

In [96]:
import pandas as pd
from sqlalchemy import create_engine

# Update with your correct schema name
schema = "County_city_info_API"
host = "127.0.0.1"
user = "root"
password = "YOUR_DB_PASSWORD"
port = 3306

# Establish the connection string
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

# Create the engine object (Required for modern Pandas to_sql)
engine = create_engine(connection_string)

# Establish connection engine
schema = "County_city_info_API"
connection_string = f'mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/{schema}'
engine = create_engine(connection_string)

In [97]:
#Step 1. Read the cities from SQL
schema = "County_city_info_api"

engine = create_engine(
    "mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/County_city_info_API"
)

query = text("""
SELECT
    city_id,
    latitude,
    longitude
FROM fact_list
""")

cities = pd.read_sql(query, engine)

cities.head()

   city_id  latitude  longitude
0        1   52.5167    13.3833
1        2   53.5500    10.0000
2        3   50.1136     8.6797
3        4   48.1372    11.5755
4        5   50.9422     6.9578

Now want to create a function which will grap the latitude and longitude for each city

updating the database with this new table with iota

In [98]:
import requests
import pandas as pd
import time


def get_city_airports(cities, radius=50):

    URL = "https://aerodatabox.p.rapidapi.com/airports/search/location"

    HEADERS = {
        "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
        "x-rapidapi-host": "aerodatabox.p.rapidapi.com",
        "Content-Type": "application/json"
    }

    flight_data = []

    for _, city in cities.iterrows():

        querystring = {
            "lat": str(city["latitude"]),
            "lon": str(city["longitude"]),
            "radiuskm": str(radius),
            "limit": "10",
            "withFlightInfoOnly": "true"
        }

        response = requests.get(
            URL,
            headers=HEADERS,
            params=querystring
        )

        # Handle rate limits
        if response.status_code == 429:
            print(f"Rate limit for city {city['city_id']}, waiting...")
            time.sleep(5)

            response = requests.get(
                URL,
                headers=HEADERS,
                params=querystring
            )

        print(
            "City:",
            city["city_id"],
            "Status:",
            response.status_code
        )

        if response.status_code != 200:
            continue

        for airport in response.json().get("items", []):

            flight_data.append({
                "city_id": int(city["city_id"]),
                "iata": airport.get("iata")
            })

        # Avoid hitting API limits
        time.sleep(1)

    return pd.DataFrame(flight_data)

In [99]:
flight_data = get_city_airports(cities.head(10), radius=50)

flight_data

City: 1.0 Status: 200
City: 2.0 Status: 200
City: 3.0 Status: 200
Rate limit for city 4.0, waiting...
City: 4.0 Status: 200
City: 5.0 Status: 200

   city_id iata
0        1  TXL
1        1  BER
2        2  HAM
3        3  FRA
4        4  MUC
5        5  CGN
6        5  DUS

In [103]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/County_city_info_API"
)

flight_data.to_sql(
    "flight_iata",
    engine,
    if_exists="append",
    index=False
)

7

### Now getting Arrivals information:

In [107]:
import requests
date = datetime.now().date()
time_1 = "00:00"
time_2 = "11:59"
iata = "GSO"

url = f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/{iata}/{date}T{time_1}/{date}T{time_2}"

querystring = {"withLeg":"true","direction":"Arrival","withCancelled":"true","withCodeshared":"true","withCargo":"true","withPrivate":"true","withLocation":"false"}

headers = {
	"x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'arrivals': [{'departure': {'airport': {'icao': 'KPHL', 'iata': 'PHL', 'name': 'Philadelphia', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 02:10Z', 'local': '2026-07-26 22:10-04:00'}, 'revisedTime': {'utc': '2026-07-27 02:52Z', 'local': '2026-07-26 22:52-04:00'}, 'runwayTime': {'utc': '2026-07-27 02:52Z', 'local': '2026-07-26 22:52-04:00'}, 'terminal': 'F', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 03:58Z', 'local': '2026-07-26 23:58-04:00'}, 'revisedTime': {'utc': '2026-07-27 04:01Z', 'local': '2026-07-27 00:01-04:00'}, 'runwayTime': {'utc': '2026-07-27 04:01Z', 'local': '2026-07-27 00:01-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'AA 6012', 'callSign': 'PDT6012', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N653AE', 'modeS': 'A897E4', 'model': 'Embraer 145'}, 'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}}, {'departure': {'airport': {'icao': 'KEWR', 'iata': 'EWR', 'name': 'Newark', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 01:57Z', 'local': '2026-07-26 21:57-04:00'}, 'revisedTime': {'utc': '2026-07-27 03:54Z', 'local': '2026-07-26 23:54-04:00'}, 'runwayTime': {'utc': '2026-07-27 03:54Z', 'local': '2026-07-26 23:54-04:00'}, 'terminal': 'C', 'runway': '22R', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 03:42Z', 'local': '2026-07-26 23:42-04:00'}, 'revisedTime': {'utc': '2026-07-27 04:59Z', 'local': '2026-07-27 00:59-04:00'}, 'runwayTime': {'utc': '2026-07-27 04:59Z', 'local': '2026-07-27 00:59-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'UA 4520', 'callSign': 'GJS4520', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N501GJ', 'modeS': 'A63E46', 'model': 'Canadair Regional Jet'}, 'airline': {'name': 'United', 'iata': 'UA', 'icao': 'UAL'}}, {'departure': {'airport': {'icao': 'KCVG', 'iata': 'CVG', 'name': 'Cincinnati', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 04:16Z', 'local': '2026-07-27 00:16-04:00'}, 'revisedTime': {'utc': '2026-07-27 04:33Z', 'local': '2026-07-27 00:33-04:00'}, 'runwayTime': {'utc': '2026-07-27 04:33Z', 'local': '2026-07-27 00:33-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 05:10Z', 'local': '2026-07-27 01:10-04:00'}, 'revisedTime': {'utc': '2026-07-27 05:21Z', 'local': '2026-07-27 01:21-04:00'}, 'runwayTime': {'utc': '2026-07-27 05:21Z', 'local': '2026-07-27 01:21-04:00'}, 'quality': ['Basic', 'Live']}, 'number': '2I 821', 'callSign': 'CSB821', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N761CK', 'modeS': 'AA457B', 'model': 'Boeing 767'}, 'airline': {'name': '21 Air', 'iata': '2I', 'icao': 'CSB'}}, {'departure': {'airport': {'icao': 'KPIE', 'iata': 'PIE', 'name': 'St Petersburg-Clearwater', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 10:10Z', 'local': '2026-07-27 06:10-04:00'}, 'revisedTime': {'utc': '2026-07-27 10:20Z', 'local': '2026-07-27 06:20-04:00'}, 'runwayTime': {'utc': '2026-07-27 10:20Z', 'local': '2026-07-27 06:20-04:00'}, 'runway': '36', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 11:58Z', 'local': '2026-07-27 07:58-04:00'}, 'revisedTime': {'utc': '2026-07-27 11:57Z', 'local': '2026-07-27 07:57-04:00'}, 'runwayTime': {'utc': '2026-07-27 11:57Z', 'local': '2026-07-27 07:57-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'G4 1039', 'callSign': 'AAY1039', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N814NV', 'modeS': 'AB1978', 'model': 'Boeing 737 MAX 8'}, 'airline': {'name': 'Allegiant Air', 'iata': 'G4', 'icao': 'AAY'}}, {'departure': {'airport': {'icao': 'KTEB', 'iata': 'TEB', 'name': 'Teterboro', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 11:30Z', 'local': '2026-07-27 07:30-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:06Z', 'local': '2026-07-27 09:06-04:00'}, 'runwayTime': {'utc': '2026-07-27 13:06Z', 'local': '2026-07-27 09:06-04:00'}, 'runway': '24', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 12:41Z', 'local': '2026-07-27 08:41-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:41Z', 'local': '2026-07-27 08:41-04:00'}, 'quality': ['Basic', 'Live']}, 'number': '1I 520', 'callSign': 'EJA520', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N520QS', 'modeS': 'A68A5D', 'model': 'Cessna 680A Citation Latitude'}, 'airline': {'name': 'NetJets Aviation', 'iata': '1I', 'icao': 'EJA'}}, {'departure': {'airport': {'icao': 'KCLT', 'iata': 'CLT', 'name': 'Charlotte', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 11:25Z', 'local': '2026-07-27 07:25-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:17Z', 'local': '2026-07-27 08:17-04:00'}, 'runwayTime': {'utc': '2026-07-27 12:17Z', 'local': '2026-07-27 08:17-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 12:30Z', 'local': '2026-07-27 08:30-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:42Z', 'local': '2026-07-27 08:42-04:00'}, 'runwayTime': {'utc': '2026-07-27 12:42Z', 'local': '2026-07-27 08:42-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'AA 5793', 'callSign': 'PDT5793', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N688AE', 'modeS': 'A920F4', 'model': 'Embraer 145'}, 'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}}, {'departure': {'airport': {'icao': 'KGVL', 'iata': 'GVL', 'name': 'Gainesville', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 12:25Z', 'local': '2026-07-27 08:25-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:25Z', 'local': '2026-07-27 08:25-04:00'}, 'runwayTime': {'utc': '2026-07-27 12:25Z', 'local': '2026-07-27 08:25-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 12:44Z', 'local': '2026-07-27 08:44-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:44Z', 'local': '2026-07-27 08:44-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N5 60LX', 'callSign': 'N560LX', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N560LX', 'modeS': 'A675D2', 'model': 'Cessna 560 Citation Excel'}, 'airline': {'name': 'Unknown/Private owner'}}, {'departure': {'airport': {'icao': 'KLGA', 'iata': 'LGA', 'name': 'New York', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 11:35Z', 'local': '2026-07-27 07:35-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:39Z', 'local': '2026-07-27 09:39-04:00'}, 'terminal': 'C', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 13:24Z', 'local': '2026-07-27 09:24-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:45Z', 'local': '2026-07-27 08:45-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'DL 5125', 'callSign': 'EDV5125', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N187GJ', 'modeS': 'A15B4C', 'model': 'Canadair CRJ 900'}, 'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}}, {'departure': {'airport': {'icao': 'KALB', 'iata': 'ALB', 'name': 'Albany', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 11:29Z', 'local': '2026-07-27 07:29-04:00'}, 'revisedTime': {'utc': '2026-07-27 11:29Z', 'local': '2026-07-27 07:29-04:00'}, 'runwayTime': {'utc': '2026-07-27 11:29Z', 'local': '2026-07-27 07:29-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 12:55Z', 'local': '2026-07-27 08:55-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:55Z', 'local': '2026-07-27 08:55-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N5 43TA', 'callSign': 'N543TA', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N543TA', 'modeS': 'A66224', 'model': 'Cessna 560 Citation Excel'}, 'airline': {'name': 'Unknown/Private owner'}}, {'departure': {'airport': {'icao': 'KUNV', 'iata': 'SCE', 'name': 'State College', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 12:37Z', 'local': '2026-07-27 08:37-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:37Z', 'local': '2026-07-27 08:37-04:00'}, 'runwayTime': {'utc': '2026-07-27 12:37Z', 'local': '2026-07-27 08:37-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 12:55Z', 'local': '2026-07-27 08:55-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:55Z', 'local': '2026-07-27 08:55-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N5 42CJ', 'callSign': 'N542CJ', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N542CJ', 'modeS': 'A6DF95', 'model': 'Cessna 525B Citation CJ3'}, 'airline': {'name': 'Unknown/Private owner'}}, {'departure': {'airport': {'icao': 'KATL', 'iata': 'ATL', 'name': 'Atlanta', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 12:10Z', 'local': '2026-07-27 08:10-04:00'}, 'revisedTime': {'utc': '2026-07-27 12:29Z', 'local': '2026-07-27 08:29-04:00'}, 'runwayTime': {'utc': '2026-07-27 12:29Z', 'local': '2026-07-27 08:29-04:00'}, 'terminal': 'S', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 13:27Z', 'local': '2026-07-27 09:27-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:20Z', 'local': '2026-07-27 09:20-04:00'}, 'runwayTime': {'utc': '2026-07-27 13:20Z', 'local': '2026-07-27 09:20-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'DL 3173', 'callSign': 'DAL3173', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N717JL', 'modeS': 'A996E1', 'model': 'Boeing 717'}, 'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}}, {'departure': {'airport': {'icao': 'KDCA', 'iata': 'DCA', 'name': 'Washington', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 12:30Z', 'local': '2026-07-27 08:30-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:12Z', 'local': '2026-07-27 09:12-04:00'}, 'runwayTime': {'utc': '2026-07-27 13:12Z', 'local': '2026-07-27 09:12-04:00'}, 'terminal': '2', 'runway': '19', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 13:54Z', 'local': '2026-07-27 09:54-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:54Z', 'local': '2026-07-27 09:54-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'AA 5252', 'callSign': 'JIA5252', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N590NN', 'modeS': 'A79EA0', 'model': 'Canadair CRJ 900'}, 'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}}, {'departure': {'airport': {'icao': 'KAVL', 'iata': 'AVL', 'name': 'Asheville', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'quality': []}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 14:12Z', 'local': '2026-07-27 10:12-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:12Z', 'local': '2026-07-27 10:12-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N5 13LH', 'callSign': 'N513LH', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N513LH', 'modeS': 'A66D96', 'model': 'Beechcraft 200 Super King Air'}, 'airline': {'name': 'Unknown/Private owner'}}, {'departure': {'airport': {'icao': 'KDTW', 'iata': 'DTW', 'name': 'Detroit', 'countryCode': 'us', 'timeZone': 'America/Detroit'}, 'scheduledTime': {'utc': '2026-07-27 12:54Z', 'local': '2026-07-27 08:54-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:09Z', 'local': '2026-07-27 09:09-04:00'}, 'runwayTime': {'utc': '2026-07-27 13:09Z', 'local': '2026-07-27 09:09-04:00'}, 'terminal': 'M', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 14:41Z', 'local': '2026-07-27 10:41-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:15Z', 'local': '2026-07-27 10:15-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'DL 4966', 'callSign': 'EDV4966', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N300PQ', 'modeS': 'A320A6', 'model': 'Canadair CRJ 900'}, 'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}}, {'departure': {'airport': {'icao': 'KLGA', 'iata': 'LGA', 'name': 'New York', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 12:19Z', 'local': '2026-07-27 08:19-04:00'}, 'revisedTime': {'utc': '2026-07-27 13:41Z', 'local': '2026-07-27 09:41-04:00'}, 'runwayTime': {'utc': '2026-07-27 13:41Z', 'local': '2026-07-27 09:41-04:00'}, 'terminal': 'B', 'runway': '13', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 14:08Z', 'local': '2026-07-27 10:08-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:46Z', 'local': '2026-07-27 10:46-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'AA 4483', 'callSign': 'RPA4483', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N654RW', 'modeS': 'A89D22', 'model': 'Embraer 170'}, 'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}}, {'departure': {'airport': {'icao': 'KATL', 'iata': 'ATL', 'name': 'Atlanta', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 14:15Z', 'local': '2026-07-27 10:15-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:15Z', 'local': '2026-07-27 10:15-04:00'}, 'terminal': 'S', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 15:34Z', 'local': '2026-07-27 11:34-04:00'}, 'revisedTime': {'utc': '2026-07-27 15:06Z', 'local': '2026-07-27 11:06-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'DL 3052', 'callSign': 'DAL3052', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N896AT', 'modeS': 'AC5BB0', 'model': 'Boeing 717'}, 'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}}, {'departure': {'airport': {'icao': 'KRIC', 'iata': 'RIC', 'name': 'Richmond', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 14:50Z', 'local': '2026-07-27 10:50-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:50Z', 'local': '2026-07-27 10:50-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 15:29Z', 'local': '2026-07-27 11:29-04:00'}, 'revisedTime': {'utc': '2026-07-27 15:29Z', 'local': '2026-07-27 11:29-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N8 10JK', 'callSign': 'N810JK', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N810JK', 'modeS': 'AB0A2E', 'model': 'Bombardier Learjet 40'}, 'airline': {'name': 'Unknown/Private owner'}}, {'departure': {'airport': {'icao': 'KGSO', 'iata': 'GSO', 'name': 'Greensboro', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'quality': []}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 15:36Z', 'local': '2026-07-27 11:36-04:00'}, 'revisedTime': {'utc': '2026-07-27 15:36Z', 'local': '2026-07-27 11:36-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'WN 8750', 'callSign': 'SWA8750', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N494WN', 'modeS': 'A620F5', 'model': 'Boeing 737-700'}, 'airline': {'name': 'Southwest Airlines', 'iata': 'WN', 'icao': 'SWA'}}, {'departure': {'airport': {'icao': 'KILM', 'iata': 'ILM', 'name': 'Wilmington', 'countryCode': 'us', 'timeZone': 'America/New_York'}, 'scheduledTime': {'utc': '2026-07-27 14:55Z', 'local': '2026-07-27 10:55-04:00'}, 'revisedTime': {'utc': '2026-07-27 14:55Z', 'local': '2026-07-27 10:55-04:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-07-27 15:55Z', 'local': '2026-07-27 11:55-04:00'}, 'revisedTime': {'utc': '2026-07-27 15:55Z', 'local': '2026-07-27 11:55-04:00'}, 'quality': ['Basic', 'Live']}, 'number': 'N9 39WB', 'callSign': 'N939WB', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'N939WB', 'model': 'Cirrus SR-22'}, 'airline': {'name': 'Unknown/Private owner'}}]}

In [105]:
response.url

'https://aerodatabox.p.rapidapi.com/flights/airports/iata/GSO/2026-07-27T00:00/2026-07-27T11:59?withLeg=true&direction=Arrival&withCancelled=true&withCodeshared=true&withCargo=true&withPrivate=true&withLocation=false'

In [108]:
flights = response.json()
flights

{'arrivals': [{'departure': {'airport': {'icao': 'KPHL',
     'iata': 'PHL',
     'name': 'Philadelphia',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 02:10Z',
     'local': '2026-07-26 22:10-04:00'},
    'revisedTime': {'utc': '2026-07-27 02:52Z',
     'local': '2026-07-26 22:52-04:00'},
    'runwayTime': {'utc': '2026-07-27 02:52Z',
     'local': '2026-07-26 22:52-04:00'},
    'terminal': 'F',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 03:58Z',
     'local': '2026-07-26 23:58-04:00'},
    'revisedTime': {'utc': '2026-07-27 04:01Z',
     'local': '2026-07-27 00:01-04:00'},
    'runwayTime': {'utc': '2026-07-27 04:01Z',
     'local': '2026-07-27 00:01-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'AA 6012',
   'callSign': 'PDT6012',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N653AE', 'modeS': 'A897E4', 'model': 'Embraer 145'},
   'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}},
  {'departure': {'airport': {'icao': 'KEWR',
     'iata': 'EWR',
     'name': 'Newark',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 01:57Z',
     'local': '2026-07-26 21:57-04:00'},
    'revisedTime': {'utc': '2026-07-27 03:54Z',
     'local': '2026-07-26 23:54-04:00'},
    'runwayTime': {'utc': '2026-07-27 03:54Z',
     'local': '2026-07-26 23:54-04:00'},
    'terminal': 'C',
    'runway': '22R',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 03:42Z',
     'local': '2026-07-26 23:42-04:00'},
    'revisedTime': {'utc': '2026-07-27 04:59Z',
     'local': '2026-07-27 00:59-04:00'},
    'runwayTime': {'utc': '2026-07-27 04:59Z',
     'local': '2026-07-27 00:59-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'UA 4520',
   'callSign': 'GJS4520',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N501GJ',
    'modeS': 'A63E46',
    'model': 'Canadair Regional Jet'},
   'airline': {'name': 'United', 'iata': 'UA', 'icao': 'UAL'}},
  {'departure': {'airport': {'icao': 'KCVG',
     'iata': 'CVG',
     'name': 'Cincinnati',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 04:16Z',
     'local': '2026-07-27 00:16-04:00'},
    'revisedTime': {'utc': '2026-07-27 04:33Z',
     'local': '2026-07-27 00:33-04:00'},
    'runwayTime': {'utc': '2026-07-27 04:33Z',
     'local': '2026-07-27 00:33-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 05:10Z',
     'local': '2026-07-27 01:10-04:00'},
    'revisedTime': {'utc': '2026-07-27 05:21Z',
     'local': '2026-07-27 01:21-04:00'},
    'runwayTime': {'utc': '2026-07-27 05:21Z',
     'local': '2026-07-27 01:21-04:00'},
    'quality': ['Basic', 'Live']},
   'number': '2I 821',
   'callSign': 'CSB821',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N761CK', 'modeS': 'AA457B', 'model': 'Boeing 767'},
   'airline': {'name': '21 Air', 'iata': '2I', 'icao': 'CSB'}},
  {'departure': {'airport': {'icao': 'KPIE',
     'iata': 'PIE',
     'name': 'St Petersburg-Clearwater',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 10:10Z',
     'local': '2026-07-27 06:10-04:00'},
    'revisedTime': {'utc': '2026-07-27 10:20Z',
     'local': '2026-07-27 06:20-04:00'},
    'runwayTime': {'utc': '2026-07-27 10:20Z',
     'local': '2026-07-27 06:20-04:00'},
    'runway': '36',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 11:58Z',
     'local': '2026-07-27 07:58-04:00'},
    'revisedTime': {'utc': '2026-07-27 11:57Z',
     'local': '2026-07-27 07:57-04:00'},
    'runwayTime': {'utc': '2026-07-27 11:57Z',
     'local': '2026-07-27 07:57-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'G4 1039',
   'callSign': 'AAY1039',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N814NV',
    'modeS': 'AB1978',
    'model': 'Boeing 737 MAX 8'},
   'airline': {'name': 'Allegiant Air', 'iata': 'G4', 'icao': 'AAY'}},
  {'departure': {'airport': {'icao': 'KTEB',
     'iata': 'TEB',
     'name': 'Teterboro',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 11:30Z',
     'local': '2026-07-27 07:30-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:06Z',
     'local': '2026-07-27 09:06-04:00'},
    'runwayTime': {'utc': '2026-07-27 13:06Z',
     'local': '2026-07-27 09:06-04:00'},
    'runway': '24',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 12:41Z',
     'local': '2026-07-27 08:41-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:41Z',
     'local': '2026-07-27 08:41-04:00'},
    'quality': ['Basic', 'Live']},
   'number': '1I 520',
   'callSign': 'EJA520',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N520QS',
    'modeS': 'A68A5D',
    'model': 'Cessna 680A Citation Latitude'},
   'airline': {'name': 'NetJets Aviation', 'iata': '1I', 'icao': 'EJA'}},
  {'departure': {'airport': {'icao': 'KCLT',
     'iata': 'CLT',
     'name': 'Charlotte',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 11:25Z',
     'local': '2026-07-27 07:25-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:17Z',
     'local': '2026-07-27 08:17-04:00'},
    'runwayTime': {'utc': '2026-07-27 12:17Z',
     'local': '2026-07-27 08:17-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 12:30Z',
     'local': '2026-07-27 08:30-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:42Z',
     'local': '2026-07-27 08:42-04:00'},
    'runwayTime': {'utc': '2026-07-27 12:42Z',
     'local': '2026-07-27 08:42-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'AA 5793',
   'callSign': 'PDT5793',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N688AE', 'modeS': 'A920F4', 'model': 'Embraer 145'},
   'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}},
  {'departure': {'airport': {'icao': 'KGVL',
     'iata': 'GVL',
     'name': 'Gainesville',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 12:25Z',
     'local': '2026-07-27 08:25-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:25Z',
     'local': '2026-07-27 08:25-04:00'},
    'runwayTime': {'utc': '2026-07-27 12:25Z',
     'local': '2026-07-27 08:25-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 12:44Z',
     'local': '2026-07-27 08:44-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:44Z',
     'local': '2026-07-27 08:44-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N5 60LX',
   'callSign': 'N560LX',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N560LX',
    'modeS': 'A675D2',
    'model': 'Cessna 560 Citation Excel'},
   'airline': {'name': 'Unknown/Private owner'}},
  {'departure': {'airport': {'icao': 'KLGA',
     'iata': 'LGA',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 11:35Z',
     'local': '2026-07-27 07:35-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:39Z',
     'local': '2026-07-27 09:39-04:00'},
    'terminal': 'C',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 13:24Z',
     'local': '2026-07-27 09:24-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:45Z',
     'local': '2026-07-27 08:45-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'DL 5125',
   'callSign': 'EDV5125',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N187GJ',
    'modeS': 'A15B4C',
    'model': 'Canadair CRJ 900'},
   'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}},
  {'departure': {'airport': {'icao': 'KALB',
     'iata': 'ALB',
     'name': 'Albany',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 11:29Z',
     'local': '2026-07-27 07:29-04:00'},
    'revisedTime': {'utc': '2026-07-27 11:29Z',
     'local': '2026-07-27 07:29-04:00'},
    'runwayTime': {'utc': '2026-07-27 11:29Z',
     'local': '2026-07-27 07:29-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 12:55Z',
     'local': '2026-07-27 08:55-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:55Z',
     'local': '2026-07-27 08:55-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N5 43TA',
   'callSign': 'N543TA',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N543TA',
    'modeS': 'A66224',
    'model': 'Cessna 560 Citation Excel'},
   'airline': {'name': 'Unknown/Private owner'}},
  {'departure': {'airport': {'icao': 'KUNV',
     'iata': 'SCE',
     'name': 'State College',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 12:37Z',
     'local': '2026-07-27 08:37-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:37Z',
     'local': '2026-07-27 08:37-04:00'},
    'runwayTime': {'utc': '2026-07-27 12:37Z',
     'local': '2026-07-27 08:37-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 12:55Z',
     'local': '2026-07-27 08:55-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:55Z',
     'local': '2026-07-27 08:55-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N5 42CJ',
   'callSign': 'N542CJ',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N542CJ',
    'modeS': 'A6DF95',
    'model': 'Cessna 525B Citation CJ3'},
   'airline': {'name': 'Unknown/Private owner'}},
  {'departure': {'airport': {'icao': 'KATL',
     'iata': 'ATL',
     'name': 'Atlanta',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 12:10Z',
     'local': '2026-07-27 08:10-04:00'},
    'revisedTime': {'utc': '2026-07-27 12:29Z',
     'local': '2026-07-27 08:29-04:00'},
    'runwayTime': {'utc': '2026-07-27 12:29Z',
     'local': '2026-07-27 08:29-04:00'},
    'terminal': 'S',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 13:27Z',
     'local': '2026-07-27 09:27-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:20Z',
     'local': '2026-07-27 09:20-04:00'},
    'runwayTime': {'utc': '2026-07-27 13:20Z',
     'local': '2026-07-27 09:20-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'DL 3173',
   'callSign': 'DAL3173',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N717JL', 'modeS': 'A996E1', 'model': 'Boeing 717'},
   'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}},
  {'departure': {'airport': {'icao': 'KDCA',
     'iata': 'DCA',
     'name': 'Washington',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 12:30Z',
     'local': '2026-07-27 08:30-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:12Z',
     'local': '2026-07-27 09:12-04:00'},
    'runwayTime': {'utc': '2026-07-27 13:12Z',
     'local': '2026-07-27 09:12-04:00'},
    'terminal': '2',
    'runway': '19',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 13:54Z',
     'local': '2026-07-27 09:54-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:54Z',
     'local': '2026-07-27 09:54-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'AA 5252',
   'callSign': 'JIA5252',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N590NN',
    'modeS': 'A79EA0',
    'model': 'Canadair CRJ 900'},
   'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}},
  {'departure': {'airport': {'icao': 'KAVL',
     'iata': 'AVL',
     'name': 'Asheville',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 14:12Z',
     'local': '2026-07-27 10:12-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:12Z',
     'local': '2026-07-27 10:12-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N5 13LH',
   'callSign': 'N513LH',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N513LH',
    'modeS': 'A66D96',
    'model': 'Beechcraft 200 Super King Air'},
   'airline': {'name': 'Unknown/Private owner'}},
  {'departure': {'airport': {'icao': 'KDTW',
     'iata': 'DTW',
     'name': 'Detroit',
     'countryCode': 'us',
     'timeZone': 'America/Detroit'},
    'scheduledTime': {'utc': '2026-07-27 12:54Z',
     'local': '2026-07-27 08:54-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:09Z',
     'local': '2026-07-27 09:09-04:00'},
    'runwayTime': {'utc': '2026-07-27 13:09Z',
     'local': '2026-07-27 09:09-04:00'},
    'terminal': 'M',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 14:41Z',
     'local': '2026-07-27 10:41-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:15Z',
     'local': '2026-07-27 10:15-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'DL 4966',
   'callSign': 'EDV4966',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N300PQ',
    'modeS': 'A320A6',
    'model': 'Canadair CRJ 900'},
   'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}},
  {'departure': {'airport': {'icao': 'KLGA',
     'iata': 'LGA',
     'name': 'New York',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 12:19Z',
     'local': '2026-07-27 08:19-04:00'},
    'revisedTime': {'utc': '2026-07-27 13:41Z',
     'local': '2026-07-27 09:41-04:00'},
    'runwayTime': {'utc': '2026-07-27 13:41Z',
     'local': '2026-07-27 09:41-04:00'},
    'terminal': 'B',
    'runway': '13',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 14:08Z',
     'local': '2026-07-27 10:08-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:46Z',
     'local': '2026-07-27 10:46-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'AA 4483',
   'callSign': 'RPA4483',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N654RW', 'modeS': 'A89D22', 'model': 'Embraer 170'},
   'airline': {'name': 'American', 'iata': 'AA', 'icao': 'AAL'}},
  {'departure': {'airport': {'icao': 'KATL',
     'iata': 'ATL',
     'name': 'Atlanta',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 14:15Z',
     'local': '2026-07-27 10:15-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:15Z',
     'local': '2026-07-27 10:15-04:00'},
    'terminal': 'S',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 15:34Z',
     'local': '2026-07-27 11:34-04:00'},
    'revisedTime': {'utc': '2026-07-27 15:06Z',
     'local': '2026-07-27 11:06-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'DL 3052',
   'callSign': 'DAL3052',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N896AT', 'modeS': 'AC5BB0', 'model': 'Boeing 717'},
   'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}},
  {'departure': {'airport': {'icao': 'KRIC',
     'iata': 'RIC',
     'name': 'Richmond',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 14:50Z',
     'local': '2026-07-27 10:50-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:50Z',
     'local': '2026-07-27 10:50-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 15:29Z',
     'local': '2026-07-27 11:29-04:00'},
    'revisedTime': {'utc': '2026-07-27 15:29Z',
     'local': '2026-07-27 11:29-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N8 10JK',
   'callSign': 'N810JK',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N810JK',
    'modeS': 'AB0A2E',
    'model': 'Bombardier Learjet 40'},
   'airline': {'name': 'Unknown/Private owner'}},
  {'departure': {'airport': {'icao': 'KGSO',
     'iata': 'GSO',
     'name': 'Greensboro',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 15:36Z',
     'local': '2026-07-27 11:36-04:00'},
    'revisedTime': {'utc': '2026-07-27 15:36Z',
     'local': '2026-07-27 11:36-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'WN 8750',
   'callSign': 'SWA8750',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N494WN', 'modeS': 'A620F5', 'model': 'Boeing 737-700'},
   'airline': {'name': 'Southwest Airlines', 'iata': 'WN', 'icao': 'SWA'}},
  {'departure': {'airport': {'icao': 'KILM',
     'iata': 'ILM',
     'name': 'Wilmington',
     'countryCode': 'us',
     'timeZone': 'America/New_York'},
    'scheduledTime': {'utc': '2026-07-27 14:55Z',
     'local': '2026-07-27 10:55-04:00'},
    'revisedTime': {'utc': '2026-07-27 14:55Z',
     'local': '2026-07-27 10:55-04:00'},
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-07-27 15:55Z',
     'local': '2026-07-27 11:55-04:00'},
    'revisedTime': {'utc': '2026-07-27 15:55Z',
     'local': '2026-07-27 11:55-04:00'},
    'quality': ['Basic', 'Live']},
   'number': 'N9 39WB',
   'callSign': 'N939WB',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'N939WB', 'model': 'Cirrus SR-22'},
   'airline': {'name': 'Unknown/Private owner'}}]}

In [44]:
flights.keys()

dict_keys(['arrivals'])

### Extracting the most important information from arrivals

In [46]:
departure_airport_iata = flights['arrivals'][0]['departure']['airport']['iata']
departure_airport_iata

'PHL'

In [50]:
schedule_arrival_time = flights['arrivals'][0]['departure']['scheduledTime']['local']
schedule_arrival_time

'2026-07-26 22:10-04:00'

In [57]:
flight_number = flights['arrivals'][0]['number']
flight_number

'AA 6012'

In [59]:
arrival_iata = iata
arrival_iata

'GSO'

### Connecting the iata list from the sql data base

In [109]:
#Step 1. Read the cities from SQL
schema = "County_city_info_api"

engine = create_engine(
    "mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/County_city_info_API"
)

query = text("""
SELECT
    city_id,
    iata
FROM flight_iata
""")

flight_iatas = pd.read_sql(query, engine)

flight_iatas

   city_id iata
0        1  TXL
1        1  BER
2        2  HAM
3        3  FRA
4        4  MUC
5        5  CGN
6        5  DUS

### now creating a function

In [110]:
import pandas as pd
import requests
from sqlalchemy import text
from datetime import datetime

def get_arrivals(engine):
    """
    Fetch arrival flight information for all airports in the flight_iata table.

    Returns
    -------
    pandas.DataFrame
    """

    # Read city_id and IATA from SQL
    query = text("""
        SELECT city_id, iata
        FROM flight_iata
    """)

    airports = pd.read_sql(query, engine)

    date = datetime.now().date()
    time_1 = "00:00"
    time_2 = "11:59"

    headers = {
        "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
        "x-rapidapi-host": "aerodatabox.p.rapidapi.com",
        "Content-Type": "application/json"
    }

    params = {
        "withLeg": "true",
        "direction": "Arrival",
        "withCancelled": "true",
        "withCodeshared": "true",
        "withCargo": "true",
        "withPrivate": "true",
        "withLocation": "false"
    }

    arrivals_data = []

    # Loop through each airport
    for _, airport in airports.iterrows():

        city_id = airport["city_id"]
        iata = airport["iata"]

        url = (
            f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/"
            f"{iata}/{date}T{time_1}/{date}T{time_2}"
        )

        try:
            response = requests.get(
                url,
                headers=headers,
                params=params,
                timeout=30
            )
            time.sleep(15) 
            response.raise_for_status()

            flights = response.json()

            for arrival in flights.get("arrivals", []):

                arrivals_data.append({
                    "city_id": city_id,
                    "arrival_iata": iata,
                    "departure_airport_iata": arrival["departure"]["airport"]["iata"],
                    "scheduled_arrival_time": arrival["arrival"]["scheduledTime"]["local"],
                    "flight_number": arrival["number"]
                })

        except Exception as e:
            print(f"Error retrieving flights for {iata}: {e}")

    return pd.DataFrame(arrivals_data)

In [111]:
arrivals_df = get_arrivals(engine)
arrivals_df

Error retrieving flights for TXL: Expecting value: line 1 column 1 (char 0)
Error retrieving flights for BER: 'iata'
Error retrieving flights for HAM: 'iata'
Error retrieving flights for FRA: 'iata'
Error retrieving flights for CGN: 'iata'
Error retrieving flights for DUS: 'iata'

,city_id,arrival_iata,departure_airport_iata,scheduled_arrival_time,flight_number
0,1,BER,IST,2026-07-27 05:45+02:00,TK 1220
1,1,BER,CGN,2026-07-27 05:39+02:00,CGF 7228
2,1,BER,ADB,2026-07-27 06:05+02:00,XQ 966
3,1,BER,PEK,2026-07-27 06:45+02:00,HU 489
4,1,BER,ESB,2026-07-27 06:45+02:00,XQ 748
...,...,...,...,...,...
1043,5,DUS,BEY,2026-07-27 10:15+02:00,ME 247
1044,5,DUS,GOT,2026-07-27 10:50+02:00,EW 9221
1045,5,DUS,NCE,2026-07-27 10:40+02:00,EW 9423
1046,5,DUS,VIE,2026-07-27 10:45+02:00,EW 9751
1047,5,DUS,BUD,2026-07-27 10:55+02:00,EW 9783

### Removing duplicated rows and pushing to SQL_database

In [112]:
#confirming how many rows were duplicated
duplicates = arrivals_df[arrivals_df.duplicated()]
print(len(duplicates))

9

In [113]:
arrivals_clean = arrivals_df.drop_duplicates()
arrivals_clean

,city_id,arrival_iata,departure_airport_iata,scheduled_arrival_time,flight_number
0,1,BER,IST,2026-07-27 05:45+02:00,TK 1220
1,1,BER,CGN,2026-07-27 05:39+02:00,CGF 7228
2,1,BER,ADB,2026-07-27 06:05+02:00,XQ 966
3,1,BER,PEK,2026-07-27 06:45+02:00,HU 489
4,1,BER,ESB,2026-07-27 06:45+02:00,XQ 748
...,...,...,...,...,...
1043,5,DUS,BEY,2026-07-27 10:15+02:00,ME 247
1044,5,DUS,GOT,2026-07-27 10:50+02:00,EW 9221
1045,5,DUS,NCE,2026-07-27 10:40+02:00,EW 9423
1046,5,DUS,VIE,2026-07-27 10:45+02:00,EW 9751
1047,5,DUS,BUD,2026-07-27 10:55+02:00,EW 9783

In [114]:
arrivals_clean = arrivals_clean.sort_values(
    by="scheduled_arrival_time",
    ascending=True
)
arrivals_clean

,city_id,arrival_iata,departure_airport_iata,scheduled_arrival_time,flight_number
976,5,CGN,CGN,2026-07-26 23:21+02:00,TCTOZ
979,5,CGN,VLC,2026-07-26 23:25+02:00,EW 539
981,5,CGN,FCO,2026-07-26 23:55+02:00,EW 889
975,5,CGN,PRN,2026-07-27 00:15+02:00,EW 925
977,5,CGN,PMI,2026-07-27 00:15+02:00,FR 9496
...,...,...,...,...,...
969,4,MUC,SAW,2026-07-27 11:30+02:00,PC 1019
971,4,MUC,DUS,2026-07-27 11:40+02:00,LH 2007
972,4,MUC,IST,2026-07-27 11:45+02:00,TK 1641
968,4,MUC,LHR,2026-07-27 11:55+02:00,LH 2471
973,4,MUC,SAW,2026-07-27 11:55+02:00,VF 41

In [115]:
arrivals_clean.info() #checking the format of the data before pushing to sql

<class 'pandas.core.frame.DataFrame'>
Index: 1039 entries, 976 to 973
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city_id                 1039 non-null   int64
 1   arrival_iata            1039 non-null   object
 2   departure_airport_iata  1039 non-null   object
 3   scheduled_arrival_time  1039 non-null   object
 4   flight_number           1039 non-null   object
dtypes: int64(1), object(4)
memory usage: 48.7+ KB

In [116]:
#converting to date time for scheduled_arrival_time 
arrivals_clean["scheduled_arrival_time"] = pd.to_datetime(
    arrivals_clean["scheduled_arrival_time"],
    utc=True
)
arrivals_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1039 entries, 976 to 973
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city_id                 1039 non-null   int64
 1   arrival_iata            1039 non-null   object
 2   departure_airport_iata  1039 non-null   object
 3   scheduled_arrival_time  1039 non-null   datetime64[ns, UTC]
 4   flight_number           1039 non-null   object
dtypes: datetime64[ns, UTC](1), int64(1), object(3)
memory usage: 48.7+ KB

In [117]:
# Push cleaned data to SQL data base
schema = "County_city_info_api"

engine = create_engine(
    "mysql+pymysql://root:YOUR_DB_PASSWORD@127.0.0.1:3306/County_city_info_API"
)

arrivals_clean.to_sql(
    "flight_arrivals",
    engine,
    if_exists="append",
    index=False
)

1039